
  const data = (window.DASHBOARD_DATA || {companies:[]}).companies;
  let chosenState='', chosenDistrict='', mapLayer, districtLayer, indiaGeo, statesGeo, districts=[], states=[];
  const $=id=>document.getElementById(id), fmt=n=>new Intl.NumberFormat('en-IN').format(n), esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const themeToggle = $('themeToggle');
  function applyTheme(theme){ document.body.dataset.theme = theme; themeToggle.textContent = theme === 'light' ? 'Black' : 'White'; }
  const savedTheme = localStorage.getItem('dashboardTheme') || 'dark';
  applyTheme(savedTheme);
  themeToggle.addEventListener('click', ()=>{ const next = document.body.dataset.theme === 'light' ? 'dark' : 'light'; applyTheme(next); localStorage.setItem('dashboardTheme', next); });
  const map=L.map('map',{zoomControl:true,scrollWheelZoom:true,fadeAnimation:true,zoomAnimation:true,preferCanvas:true}).setView([22.6,79.7],5);
  map.zoomControl.setPosition('topleft');
  map.createPane('statePane').style.zIndex=350;
  map.createPane('districtPane').style.zIndex=375;
  map.createPane('labelPane').style.zIndex=450;
  const labelLayer = L.layerGroup().addTo(map);
  L.tileLayer('https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png',{maxZoom:10,attribution:''}).addTo(map);
  const districtCounts=new Map();
  function rebuildDistrictCounts(){ districtCounts.clear(); data.forEach(c=>{const key=`${normalizeState(c.state)}|${String(c.district||'').toLowerCase()}`; districtCounts.set(key,(districtCounts.get(key)||0)+1);}); }
  rebuildDistrictCounts();
  const countFor=(state,district)=>districtCounts.get(`${normalizeState(state)}|${String(district||'').toLowerCase()}`)||0;
  const heatColor=count=>count===0?'#1d2534':count<25?'#124f47':count<100?'#0f766e':count<500?'#2dd4bf':'#14b8a6';
  const countLabel=count=>`${fmt(count)} ${count===1?'company':'companies'}`;
  function seedIllustrativeSMEs(geo){ const sectors=['AgriTech','FinTech','HealthTech','Retail','EdTech','CleanTech','Logistics Tech','Business Services']; const suffixes=['Enterprise Labs','Digital Works','Green Solutions','Supply Network']; const firstNames=['Aarav','Diya','Kabir','Meera','Rohan','Anaya','Ishaan','Kavya']; const existing=new Set(data.map(c=>`${normalizeState(c.state)}|${String(c.district||'').toLowerCase()}`)); geo.features.forEach(f=>{const state=normalizeState(f.properties.st_nm), district=String(f.properties.district||'').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase()); if(!state||!district||existing.has(`${state}|${district.toLowerCase()}`)) return; const seed=[...`${state}${district}`].reduce((n,ch)=>n+ch.charCodeAt(0),0); const total=(seed%3)+1; for(let i=0;i<total;i++){const sector=sectors[(seed+i)%sectors.length], name=`${district} ${suffixes[(seed+i)%suffixes.length]}`; data.push({name,domain:`${district.toLowerCase().replace(/[^a-z0-9]+/g,'')}-${i+1}.example`,state,district,city:district,founded:String(2015+(seed+i)%10),sector,stage:'Demo SME',funded:i%2?'No':'Yes',funding:'',employees:String(8+(seed+i)%80),website:'',linkedin:'',description:`Illustrative SME record for the ${district}, ${state} ecosystem.`,founders:[{name:firstNames[(seed+i)%firstNames.length]+' Sharma',title:'Founder & CEO',linkedin:''}],isDemo:true}); }}); rebuildDistrictCounts(); }
  function normalizeState(raw){ return String(raw||'').trim() === 'Telangana' ? 'Telangana' : String(raw||'').trim(); }
  function featureName(properties){ return normalizeState(properties.NAME_1||properties.ST_NM||properties.st_nm||properties.State_Name||properties.state||properties.name||properties.Name); }
  function districtName(layer){ return String(layer.feature.properties.D_N||layer.feature.properties.DISTRICT||layer.feature.properties.district||'').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase()); }
  function refreshDistrictMenu(){ $('districtSelect').innerHTML='<option value="">All districts</option>'+districts.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join(''); }
  function refreshStateMenu(){ $('stateSelect').innerHTML='<option value="">Select state</option>'+states.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join(''); }
  const districtLayerCache = {};
  function buildStateGeoJSON(geo){ const groups={}; geo.features.forEach(feature=>{ const state=normalizeState(featureName(feature.properties)); if(!state||!feature.geometry) return; const geom=feature.geometry; groups[state]=groups[state]||{type:'Feature',properties:{state},geometry:{type:'MultiPolygon',coordinates:[]}}; if(geom.type==='Polygon'){ groups[state].geometry.coordinates.push(geom.coordinates); } else if(geom.type==='MultiPolygon'){ groups[state].geometry.coordinates.push(...geom.coordinates); }}); return {type:'FeatureCollection',features:Object.values(groups)}; }
  function computeCentroid(coords){ if(!Array.isArray(coords) || !coords.length || !Array.isArray(coords[0])) return null; const ring=coords[0]; if(!Array.isArray(ring) || ring.length < 3) return null; let area=0,x=0,y=0; for(let i=0,j=ring.length-1;i<ring.length;j=i++){ const [x0,y0]=ring[j]||[]; const [x1,y1]=ring[i]||[]; if (typeof x0 !== 'number' || typeof y0 !== 'number' || typeof x1 !== 'number' || typeof y1 !== 'number') continue; const f=x0*y1-x1*y0; area += f; x += (x0+x1)*f; y += (y0+y1)*f; } if(!area) return Array.isArray(ring[0]) && ring[0].length===2 ? ring[0] : null; return [x/(3*area), y/(3*area)]; }
  function featureCentroid(feature){ if(!feature||!feature.geometry) return null; const geom=feature.geometry; if(geom.type==='Polygon') return computeCentroid(geom.coordinates); if(geom.type==='MultiPolygon'){ let best=null,bestArea=0; geom.coordinates.forEach(polygon=>{ if(!Array.isArray(polygon) || !polygon.length) return; const centroid=computeCentroid(polygon); if(!centroid) return; const ring=polygon[0]; if(!Array.isArray(ring) || ring.length < 3) return; let area=0; for(let i=0,j=ring.length-1;i<ring.length;j=i++){ const [x0,y0]=ring[j]||[]; const [x1,y1]=ring[i]||[]; if (typeof x0 !== 'number' || typeof y0 !== 'number' || typeof x1 !== 'number' || typeof y1 !== 'number') continue; area += x0*y1-x1*y0; } area = Math.abs(area)/2; if(area>bestArea){ bestArea=area; best=centroid; } }); return best; } return null; }
  function createStateLabels(geo){ labelLayer.clearLayers(); geo.features.forEach(feature=>{ const state=normalizeState(featureName(feature.properties)); const centroid=featureCentroid(feature); if(!state||!centroid) return; labelLayer.addLayer(L.marker(centroid,{pane:'labelPane',interactive:false,icon:L.divIcon({className:'state-label',html:`<span>${esc(state).toUpperCase()}</span>`,iconSize:[120,20],iconAnchor:[60,10]})})); }); }
  const stateStyle = feature=>({color:'#8b98a8',weight:1.8,fillColor:'rgba(248,250,252,0.92)',fillOpacity:1,opacity:0.98,stroke:true,fill:true,lineCap:'round',lineJoin:'round',smoothFactor:1});
  const fadedStateStyle = feature=>({color:'#c2cad6',weight:1.4,fillColor:'rgba(255,255,255,0.84)',fillOpacity:1,opacity:0.66,stroke:true,fill:true,lineCap:'round',lineJoin:'round',smoothFactor:1});
  function applyStateSelectionStyle(){ if(!mapLayer) return; mapLayer.eachLayer(l=>{ const layerState=normalizeState(featureName(l.feature.properties)); const selected=chosenState && layerState===chosenState; l.setStyle(selected?{color:'#14b8a6',weight:2.6,fillColor:'rgba(20,184,166,0.14)',fillOpacity:1,opacity:0.95,stroke:true,lineCap:'round',lineJoin:'round',smoothFactor:1}:chosenState?fadedStateStyle(l.feature):stateStyle(l.feature)); }); }
  function makeStateLayer(state){ if(!indiaGeo) return; if(districtLayer){ map.removeLayer(districtLayer); districtLayer=null; } if(districtLayerCache[state]){ districtLayer=districtLayerCache[state]; } else { districtLayer=L.geoJSON(indiaGeo,{pane:'districtPane',filter:f=>normalizeState(featureName(f.properties))===state&&Boolean(f.properties.district),style:{color:'rgba(155,169,184,0.9)',weight:1.05,fillColor:'transparent',fillOpacity:0,opacity:0.95,lineCap:'round',lineJoin:'round',smoothFactor:1},onEachFeature:(f,l)=>{const name=districtName(l), count=countFor(state,name); l.bindTooltip(`${name} · ${countLabel(count)}`,{sticky:true}); l.on({mouseover:()=>l.setStyle({color:'#14b8a6',weight:1.8}),mouseout:()=>districtLayer.resetStyle(l),click:()=>selectDistrict(name)});}}); districtLayerCache[state]=districtLayer; }
    districts=[...new Set(districtLayer.getLayers().map(districtName).filter(Boolean))].sort(); }
  function selectState(name){ chosenState=normalizeState(name); chosenDistrict=''; $('stateSelect').value=chosenState; $('districtSelect').disabled=!chosenState; if(chosenState){ makeStateLayer(chosenState); refreshDistrictMenu(); applyStateSelectionStyle(); const selectedLayer = mapLayer.getLayers().find(l=>normalizeState(featureName(l.feature.properties))===chosenState); if(selectedLayer){ map.flyToBounds(selectedLayer.getBounds(),{padding:[42,42],duration:0.9,maxZoom:7}); } if(districtLayer){ districtLayer.addTo(map); } } else { if(districtLayer) map.removeLayer(districtLayer); $('districtSelect').innerHTML='<option value="">Select district</option>'; if(mapLayer){ mapLayer.resetStyle(); map.fitBounds(mapLayer.getBounds(),{padding:[28,28],maxZoom:6}); } labelLayer.clearLayers(); createStateLabels(statesGeo); map.flyTo([22.6,79.7],5,{duration:0.8}); } update(); }
  function selectDistrict(name){ chosenDistrict=name; $('districtSelect').value=name; const count=countFor(chosenState,name); if(districtLayer){ districtLayer.eachLayer(l=>{ const selected=districtName(l)===name; l.setStyle({color:selected?'#14b8a6':'rgba(155,169,184,0.9)',weight:selected?1.8:1.05,fillOpacity:selected?0.18:0}); if(selected){ map.flyToBounds(l.getBounds(),{padding:[54,54],maxZoom:9,duration:0.8}); l.bindPopup(`<strong>${esc(name)}</strong><br><span style="color:#b3bbcc">${esc(chosenState)} · ${esc(countLabel(count))}</span>`,{closeButton:false,autoClose:true}).openPopup(); } }); } update(); }
  $('stateSelect').onchange=e=>selectState(e.target.value); $('districtSelect').onchange=e=>selectDistrict(e.target.value); $('search').oninput=update; $('sectorSelect').onchange=update;
  const sectorKey=c=>(c.sector||'Unclassified').split(',')[0].split('>')[0].trim()||'Unclassified';
  function filtered(){ const q=$('search').value.toLowerCase().trim(), sector=$('sectorSelect').value; return data.filter(c=>c.state===chosenState && (!chosenDistrict||c.district===chosenDistrict) && (!sector||sectorKey(c)===sector) && (!q||[c.name,c.domain,c.sector,...(c.founders||[]).map(f=>f.name+' '+f.title)].join(' ').toLowerCase().includes(q))); }
  function update(){ const all=data.filter(c=>c.state===chosenState && (!chosenDistrict||c.district===chosenDistrict)); const sectors=[...new Set(all.map(sectorKey))].sort(); const keep=$('sectorSelect').value; $('sectorSelect').innerHTML='<option value="">All sector domains</option>'+sectors.map(s=>`<option ${s===keep?'selected':''} value="${esc(s)}">${esc(s)}</option>`).join(''); const rows=filtered(), founders=new Set(rows.flatMap(c=>(c.founders||[]).map(f=>f.name))).size; $('companyCount').textContent=chosenState?fmt(all.length):'—'; $('founderCount').textContent=chosenState?fmt(founders):'—'; $('sectorCount').textContent=chosenState?fmt(sectors.length):'—'; const place=chosenDistrict?`${chosenDistrict}, ${chosenState}`:chosenState; $('title').textContent=chosenState?place:'Choose a state'; $('subtitle').textContent=chosenState?`Hyderabad records are source data; other districts use clearly labelled illustrative Demo SME records. Filter by district, sector domain, or search.`:'Select a state from the map or the menu to explore its business ecosystem.'; $('resultLabel').textContent=chosenState?`${fmt(rows.length)} companies shown${chosenDistrict?' in '+chosenDistrict:''}`:'No state selected'; $('companyList').innerHTML=rows.length?rows.slice(0,100).map(c=>`<article class="company"><div class="company-head"><div><h3>${esc(c.name)}</h3>${c.website?`<a target="_blank" rel="noreferrer" href="${esc(c.website.startsWith('http')?c.website:'https://'+c.website)}">${esc(c.domain||c.website)}</a>`:''}</div>${c.stage?`<span class="tag">${esc(c.stage)}</span>`:''}</div>${c.description?`<p>${esc(c.description)}</p>`:''}<div class="meta"><span>Sector: ${esc(sectorKey(c))}</span>${c.domain?`<span>Domain: ${esc(c.domain)}</span>`:''}${c.founded?`<span>Founded ${esc(c.founded)}</span>`:''}${c.employees?`<span>${esc(c.employees)} employees</span>`:''}${c.funded==='Yes'?'<span>Funded</span>':''}</div>${(c.founders||[]).length?`<div class="founders"><b>Founders / leadership</b>${c.founders.map(f=>`<div class="founder">${f.linkedin?`<a target="_blank" rel="noreferrer" href="${esc(f.linkedin)}">${esc(f.name)}</a>`:esc(f.name)} ${f.title?`<em>· ${esc(f.title)}</em>`:''}</div>`).join('')}</div>`:''}</article>`).join('')+(rows.length>100?`<div class="empty">Showing the first 100 matches. Refine the filters to focus the list.</div>`:''):`<div class="empty">No company records are available in this district.</div>`; }
  fetch('https://raw.githubusercontent.com/udit-001/india-maps-data/master/geojson/india.geojson').then(r=>r.json()).then(geo=>{indiaGeo=geo; seedIllustrativeSMEs(geo); statesGeo=buildStateGeoJSON(geo); states=[...new Set(statesGeo.features.map(f=>normalizeState(f.properties.state)).filter(Boolean))].sort(); refreshStateMenu(); mapLayer=L.geoJSON(statesGeo,{pane:'statePane',style:stateStyle,onEachFeature:(f,l)=>{const state=normalizeState(f.properties.state); l.bindTooltip(`${state}`,{sticky:true,offset:[0,-8]}); l.on({mouseover:()=>{l.setStyle({fillOpacity:0.18,weight:2.4}); map.getContainer().style.cursor='pointer';},mouseout:()=>{ map.getContainer().style.cursor='grab'; if(chosenState) applyStateSelectionStyle(); else mapLayer.resetStyle(l); },click:()=>selectState(state)});}}).addTo(map); createStateLabels(statesGeo); const indiaBounds = mapLayer.getBounds(); map.fitBounds(indiaBounds.pad(0.08),{padding:[28,28],maxZoom:6}); map.setMaxBounds(indiaBounds.pad(0.12));});
  update();
  